### ISSUE TITLE
The package doesn't support null safety

### ISSUE THREAD

**Issue by aquintiliano** [MaikuB/master_detail_scaffold#7]
I am trying to use your package but I am getting this error when I try to run it:
```
Error: Cannot run with sound null safety, because the following dependencies
don't support null safety:                                              
                                                                        
 - package:master_detail_scaffold                                       
                                                                        
For solutions, see https://dart.dev/go/unsound-null-safety              
Unhandled exception:                                                    
Bad state: Unsupported Null Safety mode NonNullableByDefaultCompiledMode.Invalid, in null.
#0      ProgramCompiler.emitModule (package:dev_compiler/src/kernel/compiler.dart:439:9)
#1      JavaScriptBundler.compile (package:frontend_server/src/javascript_bundle.dart:146:33)
#2      FrontendCompiler.writeJavascriptBundle (package:frontend_server/frontend_server.dart:638:47)
<asynchronous suspension>                                               
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:549:9)
<asynchronous suspension>                                               
#4      listenAndCompile.<anonymous closure> (package:frontend_server/frontend_server.dart:1119:11)
<asynchronous suspension>                                               
the Dart compiler exited unexpectedly.      
```

**Comment by XExistence** [comment]
Does this have a timeline? @MaikuB?

**Comment by aquintiliano** [comment]
I took a look on the code and tried to make some improvements (only on legibility and duplicity), and also fixed the null safety issue on my fork, if you are interested on maintain it

**Comment by XExistence** [comment]
Is this package no longer maintained? @MaikuB, would save a whole lot of issues in the future if the change @aquintiliano made on the fork were merged. Can he create a PR on those changes?

In the meantime @aquintiliano could you please send me the link to your fork, that would be really appreciated coz this package is the last one I need to fully migrate to null safety.

**Comment by aquintiliano** [comment]
sure, https://github.com/alandoni/emoji_picker

the code remains almost the same, I tried to not change everything haha

this is how I am using it:
```dart
 LayoutBuilder(
    builder: (context, constraints) => IntrinsicHeight(
      EmojiPicker(
          bgColor: backgroundLightColor,
          decoration: BoxDecoration(
             border: Border.all(color: borderColor),
          ),
          columns: constraints.maxWidth > 768
            ? 15
            : 6,
          defaultCategoryColor: backgroundLightColor,
          defaultCategorySelectedColor: highlightedSelectedColor,
          defaultCategoryIconColor: iconColor,
          defaultCategoryIconSelectedColor: primaryColor,
          indicatorColor: primaryColor,
          progressIndicatorColor: primaryColor,
          onEmojiSelected: (emoji, category) { },
      ),
   )
)
```

**Comment by aquintiliano** [comment]
omg, I made a mistake, the code I have changed was another repo haha, this one I just made the adjustment on the null safety actually, sorry

but the repo is here: https://github.com/alandoni/master_detail_scaffold

**Comment by MaikuB** [comment]
It's open sourced so if you need null safety then PRs are welcome though one hasn't been opened yet
